apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-http-docker          
  namespace: argocd        
spec:
  project: default
  source:
    repoURL: https://github.com/ydeyeq/node-app-http-docker.git 
    targetRevision: HEAD                                     
    path: deployment                                             
  destination:
    server: https://kubernetes.default.svc                  
    namespace: default                                       
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
