apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-http-docker
  namespace: node-app
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-http-docker
  template:
    metadata:
      labels:
        app: node-app-http-docker
    spec:
      containers:
      - name: node-app-http-docker
        image: ghcr.io/ydeyeq/node-app-http-docker:main 
        ports:
        - containerPort: 4040


---

apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
    - port: 80
      targetPort: 4040